import type { ComponentType, SVGProps } from "react";
import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Banknote,
  BookOpen,
  Bot,
  Box,
  Briefcase,
  Building,
  BuildingComplex,
  Calculator,
  Calendar,
  Car,
  ChartColumn,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  Coins,
  Compass,
  Copy,
  Cpu,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  FaceSlightlySmiling,
  File as FileGlyph,
  FileCheck,
  FileText,
  FingerprintPattern,
  Flag,
  Funnel,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  HeartPulse,
  House,
  Info,
  Key,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link as LinkGlyph,
  List,
  LifeBuoy,
  LoaderCircle,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  Moon,
  Newspaper,
  Package,
  Paperclip,
  Percent,
  Phone,
  Plane,
  Plus,
  Quote,
  Receipt,
  RefreshCw,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  Siren,
  SlidersHorizontal,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Table,
  Target,
  ThumbsUp,
  TrendingUp,
  TriangleAlert,
  Umbrella,
  Upload,
  User,
  UserCheck,
  Users,
  Wallet,
  WifiOff,
  Workflow,
  X,
  Zap
} from "lucide-react";

/**
 * Icon set of the public site: a thin wrapper over `lucide-react`, so every glyph shares one grid,
 * one stroke and one optical weight. Icons are decorative (`aria-hidden`) and inherit `currentColor`;
 * the meaning always lives in the text next to them.
 *
 * `whatsapp` has no lucide glyph and keeps the hand-drawn path of the original set.
 */

function WhatsAppGlyph(props: SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M3.8 20.2 5 16.4A8.2 8.2 0 1 1 8.2 19.5l-4.4.7Z" />
      <path d="M9 9c.3 2.5 3.5 5.7 6 6 .8.1 1.5-.6 1.5-1.4l-2-.9-1 1c-1.2-.5-2.7-2-3.2-3.2l1-1-.9-2C9.6 7.5 8.9 8.2 9 9Z" />
    </svg>
  );
}

/** Every icon the public site may use. The first 21 are the historical set and must keep working. */
export const iconNames = [
  // Historical set
  "check",
  "chevron-down",
  "chevron-right",
  "shield",
  "umbrella",
  "leaf",
  "phone",
  "whatsapp",
  "mail",
  "globe",
  "search",
  "alert",
  "info",
  "file",
  "user",
  "building",
  "star",
  "arrow-right",
  "menu",
  "close",
  "external",
  // Navigation and direction
  "arrow-left",
  "arrow-up-right",
  "chevron-left",
  "chevron-up",
  "minus",
  "plus",
  "x",
  "more-horizontal",
  // Insurance products
  "car",
  "plane",
  "heart-pulse",
  "home",
  "briefcase",
  "stethoscope",
  "life-buoy",
  "siren",
  // Trust and compliance
  "shield-check",
  "badge-check",
  "lock",
  "eye",
  "key",
  "fingerprint",
  "scale",
  "landmark",
  "flag",
  // Intelligence
  "sparkles",
  "bot",
  "lightbulb",
  "target",
  "compass",
  "zap",
  // Time and place
  "clock",
  "calendar",
  "map-pin",
  // Lists, filters and data
  "filter",
  "sliders",
  "list",
  "layout-grid",
  "table",
  "trending-up",
  "bar-chart",
  "pie-chart",
  "layers",
  "box",
  "package",
  "database",
  "server",
  "cpu",
  "git-branch",
  "workflow",
  // Money
  "calculator",
  "coins",
  "wallet",
  "receipt",
  "percent",
  "banknote",
  // People
  "users",
  "user-check",
  "handshake",
  "headphones",
  "building-2",
  // Messages and files
  "message-circle",
  "send",
  "paperclip",
  "upload",
  "download",
  "file-text",
  "file-check",
  // Status
  "check-circle",
  "x-circle",
  "alert-triangle",
  "help-circle",
  "loader",
  "refresh",
  "wifi-off",
  // Editorial
  "book-open",
  "graduation-cap",
  "newspaper",
  "quote",
  "link",
  "share",
  "copy",
  "settings",
  // Sentiment and rewards
  "award",
  "thumbs-up",
  "smile",
  "sun",
  "moon"
] as const;

export type IconName = (typeof iconNames)[number];

type GlyphProps = SVGProps<SVGSVGElement> & { size?: number | string };

const glyphs: Record<IconName, ComponentType<GlyphProps>> = {
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  shield: Shield,
  umbrella: Umbrella,
  leaf: Leaf,
  phone: Phone,
  whatsapp: WhatsAppGlyph,
  mail: Mail,
  globe: Globe,
  search: Search,
  alert: CircleAlert,
  info: Info,
  file: FileGlyph,
  user: User,
  building: Building,
  star: Star,
  "arrow-right": ArrowRight,
  menu: Menu,
  close: X,
  external: ExternalLink,
  "arrow-left": ArrowLeft,
  "arrow-up-right": ArrowUpRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  minus: Minus,
  plus: Plus,
  x: X,
  "more-horizontal": Ellipsis,
  car: Car,
  plane: Plane,
  "heart-pulse": HeartPulse,
  home: House,
  briefcase: Briefcase,
  stethoscope: Stethoscope,
  "life-buoy": LifeBuoy,
  siren: Siren,
  "shield-check": ShieldCheck,
  "badge-check": BadgeCheck,
  lock: Lock,
  eye: Eye,
  key: Key,
  fingerprint: FingerprintPattern,
  scale: Scale,
  landmark: Landmark,
  flag: Flag,
  sparkles: Sparkles,
  bot: Bot,
  lightbulb: Lightbulb,
  target: Target,
  compass: Compass,
  zap: Zap,
  clock: Clock,
  calendar: Calendar,
  "map-pin": MapPin,
  filter: Funnel,
  sliders: SlidersHorizontal,
  list: List,
  "layout-grid": LayoutGrid,
  table: Table,
  "trending-up": TrendingUp,
  "bar-chart": ChartColumn,
  "pie-chart": ChartPie,
  layers: Layers,
  box: Box,
  package: Package,
  database: Database,
  server: Server,
  cpu: Cpu,
  "git-branch": GitBranch,
  workflow: Workflow,
  calculator: Calculator,
  coins: Coins,
  wallet: Wallet,
  receipt: Receipt,
  percent: Percent,
  banknote: Banknote,
  users: Users,
  "user-check": UserCheck,
  handshake: Handshake,
  headphones: Headphones,
  "building-2": BuildingComplex,
  "message-circle": MessageCircle,
  send: Send,
  paperclip: Paperclip,
  upload: Upload,
  download: Download,
  "file-text": FileText,
  "file-check": FileCheck,
  "check-circle": CircleCheck,
  "x-circle": CircleX,
  "alert-triangle": TriangleAlert,
  "help-circle": CircleQuestionMark,
  loader: LoaderCircle,
  refresh: RefreshCw,
  "wifi-off": WifiOff,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  newspaper: Newspaper,
  quote: Quote,
  link: LinkGlyph,
  share: Share,
  copy: Copy,
  settings: Settings,
  award: Award,
  "thumbs-up": ThumbsUp,
  smile: FaceSlightlySmiling,
  sun: Sun,
  moon: Moon
};

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, "name" | "children"> {
  name: IconName;
  /** Rendered square size in pixels. 20 in body copy, 24 in a tile, 32+ in an empty state. */
  size?: number;
}

export function Icon({ name, size = 20, className, ...rest }: IconProps) {
  const Glyph = glyphs[name];
  return (
    <Glyph
      aria-hidden="true"
      focusable="false"
      className={className ? `am-icon ${className}` : "am-icon"}
      width={size}
      height={size}
      strokeWidth={size >= 32 ? 1.75 : 2}
      {...rest}
    />
  );
}
