export const ErrorCodes = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  MFA_REQUIRED: "MFA_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  TENANT_SCOPE_DENIED: "TENANT_SCOPE_DENIED",
  EXPORT_DENIED: "EXPORT_DENIED",
  CONSENT_REQUIRED: "CONSENT_REQUIRED",
  LICENSE_BLOCKED: "LICENSE_BLOCKED",
  COUNTRY_DISABLED: "COUNTRY_DISABLED",
  PRODUCT_DISABLED: "PRODUCT_DISABLED",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  ROUTING_NOT_ELIGIBLE: "ROUTING_NOT_ELIGIBLE",
  AI_DISABLED: "AI_DISABLED",
  RATE_LIMITED: "RATE_LIMITED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  /** Spec 050: catalogue administration refusals. */
  CATALOG_FLAG_NOT_TOGGLEABLE: "CATALOG_FLAG_NOT_TOGGLEABLE",
  CATALOG_UPDATE_CONFLICT: "CATALOG_UPDATE_CONFLICT",
  ACTIVATION_BLOCKED: "ACTIVATION_BLOCKED",
  QUOTE_FORM_REQUIRED: "QUOTE_FORM_REQUIRED",
  CONSENT_TEXT_REQUIRED: "CONSENT_TEXT_REQUIRED",
  CONSENT_TEXT_INVALID: "CONSENT_TEXT_INVALID",
  REGULATORY_REGIME_INVALID: "REGULATORY_REGIME_INVALID",
  QUOTE_FORM_LANGUAGE_UNAVAILABLE: "QUOTE_FORM_LANGUAGE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
