export const ErrorCodes = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  MFA_REQUIRED: "MFA_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  TENANT_SCOPE_DENIED: "TENANT_SCOPE_DENIED",
  EXPORT_DENIED: "EXPORT_DENIED",
  CONSENT_REQUIRED: "CONSENT_REQUIRED",
  LICENSE_BLOCKED: "LICENSE_BLOCKED",
  COUNTRY_DISABLED: "COUNTRY_DISABLED",
  PRODUCT_DISABLED: "PRODUCT_DISABLED",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  ROUTING_NOT_ELIGIBLE: "ROUTING_NOT_ELIGIBLE",
  AI_DISABLED: "AI_DISABLED",
  RATE_LIMITED: "RATE_LIMITED",
  VALIDATION_FAILED: "VALIDATION_FAILED"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
